# PlatformIO pre-build script: embed main/web_ui.html as a C array.
#
# Replaces ESP-IDF EMBED_TXTFILES, whose generated .S lives in the build dir
# and breaks PlatformIO's codemodel -> object mapping (doubled .pio/build path)
# when src_dir = main. Generating web_ui_html.c into the source tree sidesteps
# that; the file is a build artifact and is git-ignored.

Import("env")  # noqa: F821

from pathlib import Path

src = Path(env["PROJECT_DIR"]) / "main" / "web_ui.html"
out = Path(env["PROJECT_DIR"]) / "main" / "web_ui_html.c"

data = src.read_bytes()
lines = []
for i in range(0, len(data), 12):
    chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
    lines.append(f"    {chunk},")

content = (
    "/* Auto-generated by embed_web_ui.py from web_ui.html. Do not edit. */\n"
    "\n"
    "const char web_ui_html_start[] = {\n" + "\n".join(lines) + "\n};\n"
    "\n"
    "const unsigned int web_ui_html_size = sizeof(web_ui_html_start);\n"
)

if not out.exists() or out.read_text() != content:
    out.write_text(content)
    print(f"embed_web_ui: regenerated {out.name} ({len(data)} bytes)")
