[platformio]
default_envs = seeedmote_gateway
src_dir = main

[env:seeedmote_gateway]
platform = espressif32
framework = espidf
board = seeed_xiao_esp32s3
board_build.partitions = partitions.csv
build_flags =
    -DGATEWAY_FW_VERSION=\"2026.06.08\"
monitor_speed = 115200
monitor_filters = direct
